<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>CPG.Api</RootNamespace>
    <AssemblyName>CPG.Api</AssemblyName>
    <UserSecretsId>cpg-enterprises-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />

    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />

    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" />
    <PackageReference Include="Serilog.AspNetCore" />

    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CPG.Application\CPG.Application.csproj" />
    <ProjectReference Include="..\CPG.Infrastructure\CPG.Infrastructure.csproj" />
  </ItemGroup>

</Project>
